'use client';

import React from 'react';
import TopBar from './components/TopBar';
import Header from './components/Header';
import BrowseCategories from './components/BrowseCategories';
import Footer from './components/Footer';
import '../globals.css'; // Assuming you have global styles

const CustomerLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Store2U</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <div className="min-h-screen bg-white flex flex-col">
          <TopBar />
          <Header />
          <main className="flex-grow">
            {/* <BrowseCategories /> */}
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default CustomerLayout;
